create table if not exists public.proposal_submission_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  email_hash text not null,
  accepted boolean not null default true,
  reason text not null default 'accepted',
  created_at timestamptz not null default now()
);

alter table public.proposal_submission_attempts enable row level security;

revoke all on table public.proposal_submission_attempts from anon, authenticated;

-- Lead creation should go through the Next.js Server Action so Turnstile and
-- rate limiting cannot be bypassed with the public Supabase key.
revoke insert on table public.leads from anon, authenticated;

create index if not exists proposal_submission_attempts_ip_created_idx
  on public.proposal_submission_attempts (ip_hash, created_at desc);

create index if not exists proposal_submission_attempts_email_created_idx
  on public.proposal_submission_attempts (email_hash, created_at desc);

create index if not exists proposal_submission_attempts_created_idx
  on public.proposal_submission_attempts (created_at desc);
